BLUE={'A':'deep cobalt blue similar to Pantone 2728C','B':'bright cobalt blue leaning azure, similar to Pantone 2935C'}
def common(b): return f'Luxury skincare packaging for the brand "TERNOVA" (exact spelling, 7 capital letters). Tall slim carton and opaque cylindrical bottle in flat {BLUE[b]}, not ultramarine, not navy, not purple. All surfaces flat matte like uncoated laminated paper, light-absorbing, diffuse, zero sheen. The single reflective element: the "TERNOVA" wordmark in mirror-polished yellow-gold flat hot foil with bold strokes, no embossing, catching one crisp highlight, placed in the upper third of the carton front. Cap: brushed satin yellow-gold aluminum, low sheen, duller than the logo. Photorealistic product photography, true-to-life color. Avoid: rose gold, copper, bronze, silver, glossy carton, gradient, wave pattern, concentric circles, extra text, misspelled logo.'
SHOTS={
 'shot1':('3:4',True,'Front view of the tall slim rectangular carton standing next to the bottle with gold cap, on a light grey seamless background. Carton front, top to bottom: gold foil TERNOVA logo, one small white tag line "CLINICALLY TESTED", a large realistic render of the bottle filling the lower half, a white product-name band overlapping the render reading "FIRMING SERUM", net quantity "50 mL / 1.69 fl oz" in small white text at the very bottom. Soft studio light from upper left creating one bright highlight on the gold foil logo while matte surfaces show no reflections.'),
 'shot2':('1:1',True,'Close-up macro of the carton front tilted at 40 degrees, raking light skimming the surface, the flat mirror-gold "TERNOVA" foil logo glows with a sharp specular highlight while the surrounding matte blue stays deep and flat. Shallow depth of field.'),
 'shot3':('3:4',False,'Straight-on flat view of the narrow side panel of a tall matte cobalt blue skincare carton, flat uncoated-paper matte finish, no foil, no logo. Top to bottom: a small white circular outline badge with tiny text; a very large white sans-serif "94%" with two short lines of white text beside it reading "HAD VISIBLY FIRMER SKIN"; a tiny label "UNRETOUCHED IMAGES"; two stacked close-up skin photos with thin white borders and a thin white circle highlighting the same area, captioned "BEFORE" and "AFTER 4 WEEKS"; a line of tiny white test-condition text at the bottom. Even diffuse lighting, no reflections, packaging mockup style.'),
 'shot4':('9:16',True,'Casual iPhone photo in a pharmacy aisle: a left hand holds the tall slim carton at chest height, turned at a three-quarter angle so both the front (gold TERNOVA logo at top, bottle render, white product name band) and the right side panel (large white "94%", two stacked before/after skin photos) are visible together. White and beige skincare shelves blurred behind, cool white store lighting, the gold foil logo catches the ceiling light. Natural phone-camera look, slight noise, no retouching.'),
 'shot7':('4:3',False,'Two identical luxury skincare sets for the brand "TERNOVA" side by side on a clean light grey background: LEFT tall slim carton and opaque bottle in flat matte bright cobalt blue, RIGHT identical carton and bottle in flat matte deep crimson red. Same layout, same mirror-polished yellow-gold flat foil "TERNOVA" logo in the upper third, same brushed satin yellow-gold caps. Flat matte bodies with no sheen, only the logos reflect. Soft even studio light, symmetrical composition, photorealistic. Avoid rose gold, copper, purple.'),
}
def jobs():
    out=[]
    for k,(ar,use_common,p) in SHOTS.items():
        variants=['A','B'] if k in ('shot1','shot4') else (['B'] if use_common else [None])
        for b in variants:
            prompt=(common(b)+' '+p) if use_common else p
            out.append((f'{k}{b or ""}',ar,prompt))
    return out
